[package]
name = "configs"
version = "0.0.1"
edition = "2024"

[dependencies]
secrets-manager = { git = "ssh://git@github.com/ruskit/secrets_manager.git", rev = "v0.0.0" }
serde = { version = "1.0.219", features = ["derive"]}
